reports.index:
  path: /view
  defaults: { _controller: 'Unilever\Controller\Report::indexAction' }
  
reports.view:
  path: /view/{date}
  defaults: { _controller: 'Unilever\Controller\Report::indexAction' }

reports.raw:
  path: /view/raw/{date}/{role}
  defaults: { _controller: 'Unilever\Controller\Report::indexRawAction' }