roles.index:
  path: /
  defaults: { _controller: 'Unilever\Controller\Role::indexAction' }

roles.create:
  path: /create
  defaults: { _controller: 'Unilever\Controller\Role::createAction' }
  
roles.page:
  path: /{page}
  defaults: { _controller: 'Unilever\Controller\Role::indexAction' }
  
roles.edit:
  path: /edit/{role_pk}
  defaults: { _controller: 'Unilever\Controller\Role::editAction' }
  
roles.delete:
  path: /delete/{role_pk}
  defaults: { _controller: 'Unilever\Controller\Role::deleteAction' }
  