index:
  path: /
  defaults: { _controller: 'Unilever\Controller\Index::indexAction' }
  
home:
  path: /home
  defaults: { _controller: 'Unilever\Controller\Index::homeAction' }

_login:
  path: /login
  defaults: { _controller: 'Unilever\Controller\Index::loginAction' }
  
_logout:
  path: /logout
  defaults: { _controller: 'Unilever\Controller\Index::logoutAction' }
  
questionnaire.show:
  path: /questionnaire/show
  defaults: { _controller: 'Unilever\Controller\Questionnaire::showAction' }
  
questionnaire.submit:
  path: /questionnaire/submit
  defaults: { _controller: 'Unilever\Controller\Questionnaire::submitAction' }

users:
  prefix: /users
  resource: users.yml
  
teams:
  prefix: /teams
  resource: teams.yml
  
roles:
  prefix: /roles
  resource: roles.yml
  
questions:
  prefix: /questions
  resource: questions.yml
  
recover:
  prefix: /recover
  resource: recover.yml  
  
results:
  prefix: /results
  resource: results.yml

reports:
  prefix: /reports
  resource: reports.yml